#!/bin/sh
set -e

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
    set -- apache2-foreground "$@"
fi

if [ -z "$(ls -A /mnt/apps/symfony/www)" ]; then
    cd /mnt/apps/symfony/
    symfony new www 3.4
fi

cd /mnt/apps/symfony

chmod 777 www/var/ -R

# composer install
# npm install

exec "$@"