<?php

namespace OC\PlatformBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ApplicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicationRepository extends EntityRepository
{
	public function getApplicationsWithAdvert($limit)
	{
		$qb = $this
			->createQueryBuilder('app')
			->leftJoin('app.advert', 'a')
			->addSelect('a')
			->setMaxResults($limit)
		;

		return $qb
			->getQuery()
			->getResult()
		;
	}
}
