#!/bin/bash

ROOT_PATH=/mnt/apps/symfony
ARCHIVE_PATH=/mnt/apps/.archives
CURRENT_DATE=`date +"%Y%m%d_%H%M%S"`

# Check if we have colors enabled
tput=$(which tput)
if [ -n "$tput" ]; then
    ncolors=$($tput colors)
    if [ -n "$ncolors" ] && [ "$ncolors" -ge 8 ]; then
        red="$(tput setaf 1)"
        green="$(tput setaf 2)"
        white="$(tput setaf 7)"
        whitebg="$(tput setab 7)"
        greenbg="$(tput setab 2)"
        redbg="$(tput setab 1)"
        reset="$(tput sgr0)"
    else
        red=""
        green=""
        white=""
        whitebg=""
        greenbg=""
        redbg=""
        reset=""
    fi
fi

case "$1" in
    remove|upgrade)
        echo "${greenbg}${white}Pre remove configure : '$1' ...${reset}"
        echo "${greenbg}${white}Archiving old symfony database and source in ${ARCHIVE_PATH} ...${reset}"

        echo "${greenbg}${white}Disable symfony VHost ...${reset}"
        a2dissite symfnoy.conf

        echo "${greenbg}${white}Enable Default VHost ...${reset}"
        a2ensite 000-default.conf

        echo "${greenbg}${white}Restart apache ...${reset}"
        /etc/init.d/apache2 restart

        echo "${greenbg}${white}Dumping postgresql database ...${reset}"
        pg_dump -h localhost -U postgres symfony_db > /root/${CURRENT_DATE}_dump.sql

        if [ "$1" == "remove" ]; then
            echo "${greenbg}${white}Drop database and user in postgresql ...${reset}"
            psql --username "postgres" -h 127.0.0.1 <<-EOSQL
            \set ON_ERROR_STOP TRUE
            DROP DATABASE symfony_db;
            DROP USER symfony_user;
EOSQL
            psql_exit_status=$?

            if [ $psql_exit_status != 0 ]; then
                echo "${redbg}${white}psql failed while trying to run this sql script${reset}" 1>&2
                exit $psql_exit_status
            fi
        fi

        if [ ! -d ${ARCHIVE_PATH} ]; then
            echo "${greenbg}${white}Creation of the archive folder ...${reset}"
            mkdir -p ${ARCHIVE_PATH}
        fi

        echo "${greenbg}${white}Creation of the archive of Umanager source and database ...${reset}"
        tar zcf ${ARCHIVE_PATH}/${CURRENT_DATE}_umanager.tar ${ROOT_PATH} /root/${CURRENT_DATE}_dump.sql

        if [ -d ${ROOT_PATH} ]; then
            echo "${greenbg}${white}Remove '${ROOT_PATH}' ...${reset}"
            rm -rf ${ROOT_PATH}
        fi

        echo "${greenbg}${white}Remove SQL Dump file ...${reset}"
        rm /root/${CURRENT_DATE}_dump.sql

        echo "${greenbg}${white}Remove of symfony DONE${reset}"
        ;;
    failed-upgrade)
        echo "${whitebg}${red}Pre remove failed-upgrade not implemented${reset}"
        ;;
    *)
        echo "${whitebg}${red}Pre remove called with unknown argument '$1'${reset}" >&2
        exit 1
        ;;
esac

exit 0

