#!/bin/sh
set -e

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
    set -- apache2-foreground "$@"
fi

if [ -z "$(ls -A /mnt/apps/symfony/www)" ]; then
    cd /mnt/apps/symfony/
    symfony new www 3.4
fi

cd /mnt/apps/symfony/www

chmod 777 var/ -R

chown www-data:www-data web/uploads/ -R

composer install
yarn install

while ! curl http://database:5432/ 2>&1 | grep '52'
do
	>&2 echo "Postgres is unavailable - sleeping"
	sleep 1
done

>&2 echo "Postgres is up - Run migrations"

#Create database
# php bin/console doctrine:database:create

#Show queries diff
# php bin/console doctrine:schema:update --dump-sql

#Execute queries diff
# php bin/console doctrine:schema:update --force
php bin/console doctrine:migrations:migrate --no-interaction

#Generate getter/setter entity
# php bin/console doctrine:generate:entities OCPlatformBundle:Advert

#Generate migration file
# php bin/console doctrine:migrations:diff

#Seed database
php bin/console doctrine:fixtures:load --no-interaction

#Creating admin user
php bin/console fos:user:create testuser test@example.com p@ssword
php bin/console fos:user:promote testuser ROLE_ADMIN

#Run assetic
# php bin/console assets:install --symlink
# php bin/console assetic:dump --env=prod

npm run dev

exec "$@"